### PR TITLE
Don't access s_renderInfo from the Unity thread, instead read from s_…

### PR DESCRIPTION
**Pull request by DuFF14**
…lastRenderInfo. Appears to fix the random Unity crashes.

### CODE REVIEW

**Comment by DuFF14** [comment]
@russell-taylor added. Is that the correct way to use the mutex?

**Comment by russell-taylor** [comment]
The lock_guard is a good way to do it.  Why did it get changed back to manual locking and unlocking?

**Comment by rpavlik** [comment]
yeah, you definitely want to use lock_guard instead of this last commit.

**Comment by russell-taylor** [comment]
Looks good.  The only remaining issue is that the code may get inconsistent views for the left and right eyes if the value is read in between those.  If predictive tracking is doing its job well, the estimates should be close to consistent.

**Comment by DuFF14** [comment]
Added mutex around other s_lastRenderInfo accesses that were missed. Getting confident that this minimally resolves the random crashing we were seeing. Working on https://github.com/OSVR/OSVR-Unity/issues/208 to make sure other crashing issues aren't related.

**Comment by DuFF14** [comment]
Ok, confirmed that it wasn't causing another crashing issue. Merging.

**Pull request merged**
